### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by aidanmcgaugh** [ECON368-fall2023-big-data-and-economics/big-data-class-materials#28]
There is a typo in the FAQ section: "Create a fork of this repository (called the upstream repository) if you not before", I believe this should say "if you have not before". 

In the Grading section, it says "Quality of oresentation of graphs and tables (30%): Are they well-labeled? Do they have titles? Do they have legends? Are they formatted well?" Here, "oresentation" should be "presentation"

Also, in the problem set, question 8 says "Can think of any limitations", when it should say "Can you think of any limitations"

I have attached screenshots: 

<img width="834" alt="Screen Shot 2023-10-06 at 4 29 08 PM" src="https://github.com/ECON368-fall2023-big-data-and-economics/big-data-class-materials/assets/144745197/c3c04e3b-cae2-42a6-8ef8-a7bfb9ab228e">
<img width="859" alt="Screen Shot 2023-10-06 at 4 29 30 PM" src="https://github.com/ECON368-fall2023-big-data-and-economics/big-data-class-materials/assets/144745197/3c64422b-0ba4-4984-8378-c27b16218157">
<img width="633" alt="Screen Shot 2023-10-06 at 4 29 45 PM" src="https://github.com/ECON368-fall2023-big-data-and-economics/big-data-class-materials/assets/144745197/82c9cb83-ba99-493b-8b84-2bd173fe5d9c">

**Comment by kgcsport** [comment]
Hi Aidan, 

Thank you for providing these. Please associate Issues/questions with the corresponding repository for the typo. For example, some of these correspond to Problem Set 2 and should be placed within the PS2 [Issues tab](https://github.com/ECON368-fall2023-big-data-and-economics/PS2-manager-survey/issues). 

On that, I encourage you to submit typo corrections as pull requests wherever possible so they are presented in context. This is especially true for typo corrections to the class materials page. 

I provide instructions to pull request **specific commits** in the [class materials](https://github.com/ECON368-fall2023-big-data-and-economics/big-data-class-materials#pull-request-of-a-specific-commit), so you do not send through answers to problem sets if you do not want. 

The goal is not only to have an eagle eye for typos, which you have, but also to learn best practices for getting them fixed efficiently, which is a skill that applies beyond this class.
