### ISSUE TITLE
Problem Set Grading 

### ISSUE THREAD

**Issue by Rawson-Welch** [ECON368-fall2023-big-data-and-economics/big-data-class-materials#45]
Hi Professor Coombs, 

I was wondering how the syllabus will be updated given problem set 3 becoming optional. I know you said that that problem set would not count as a drop, but I wanted to confirm that all problem sets would still accumulate to 50% of our grade and if that is the case then each problem set would become 12.5% of our grade, accounting for 2 drops and 1 optional problem set. 

Thanks, 
Rawson

**Comment by kgcsport** [comment]
Yes, that's correct. They count for 50% of the grade still.
