### ISSUE TITLE
Corrections for Group Problem Sets

### ISSUE THREAD

**Issue by jadensschrock** [ECON368-fall2023-big-data-and-economics/big-data-class-materials#46]
Hi @kgcsport,

Firstly, I raised this issue in Yuna and I's PS1 repository, but you weren't listed as a contributor the same way as you are on here and I wanted to make sure you got this message. I also wasn't sure if this question may be relevant to other people in the class. Of course feel free to remove this issue or ignore it if you did already receive it or if this is more of an individually relevant question. 

I wanted to get a little more clarification on how I should go about corrections for group problem sets. I am working on corrections for PS1 and PS2 and I know @yunawuuu  is also working on corrections for the grouped PS1. Given that it is a shared repository, do we submit corrections together, or do we each need to make forks of our repository and do our corrections this way? Thank you so much for your help and support this semester!

Best,
Jaden

**Comment by kgcsport** [comment]
Ah yes, I used a slightly different system for the first problem set -- I responded on the actual problem set as well. 

Please submit corrections together.
