### ISSUE TITLE
Edit to Open Source Content — Extra Credit Opportunity Accomplished

### ISSUE THREAD

**Issue by Rawson-Welch** [ECON368-fall2023-big-data-and-economics/big-data-class-materials#48]
Hi Kyle, 

I believe that I correctly made a pull request to random open source content on Github. I think that I tagged you in it so that you could see it, but wanted to provide an image of this here as well. Thanks. Please let me know if this does not suffice.  

![image](https://github.com/ECON368-fall2023-big-data-and-economics/big-data-class-materials/assets/144358492/066ec3c7-0df2-4826-917a-fa7551a9df7e)

**Comment by kgcsport** [comment]
Saw it, looks great.
